package sharing.com.enjoying.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class AboutUsModel {
    //Autogenerated id
    @Id
    @GeneratedValue
    Long id;

    // Attribute or variables
    private String description;

    //Default constructor
    public AboutUsModel() {
    }

    //Constructor

    public AboutUsModel(Long id, String description) {
        this.id = id;
        this.description = description;
    }

    //Getters

    public Long getId() {
        return id;
    }

    public String getDescription() {
        return description;
    }

    // Setters

    public void setId(Long id) {
        this.id = id;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
