package Final_assignment.Sharing.models;

import jakarta.persistence.*;

import java.util.Collection;

@Entity
@Table(name="users")
public class UserModel {

    //Autogenerated id
    @Id
    private String username;

    private String password;

    //ManyToMany relation

    @ManyToMany(fetch = FetchType.EAGER)
    private Collection<RoleModel> roleModels;

    //Default constructor
    public UserModel(){}

    //Constructor

    public UserModel(String username, String password, Collection<RoleModel> roleModels) {
        this.username = username;
        this.password = password;
        this.roleModels = roleModels;
    }

    //Setter

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public Collection<RoleModel> getRoleModels() {
        return roleModels;
    }

    //Getter
    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setRoleModels(Collection<RoleModel> roleModels) {
        this.roleModels = roleModels;
    }
}
